version: "3.7"
services:
  redis:
    image: redis
  test:
    build:
      context: .
    environment:
      PYTHONPATH: /app
      REDIS_RATELIMIT_DB_URL: redis://redis
    entrypoint: django-admin test --settings=tests.settings
    volumes:
      - ./:/app
    depends_on:
      - redis